### PR TITLE
Cleaned up documentation

### PR DESCRIPTION
**Pull request by gbaman**
- Cleaned up main README.md by adding better explanation of Vanillacraft and an image.
- Added proper CONTRIBUTING.md file which is correctly detected by Github.
- Reformatted Todo list as a Github Markdown table for easier reading.
- Renamed To do list to Todo-list.md.

### CODE REVIEW

**Comment by Ryan00793** [comment]
I don't like that the todo list loses depth, it looks like everything is it's own plugin. I don't care if it's not the prettiest looking thing all the rest are fine.

**Comment by gbaman** [comment]
Ahh, had thought that was just a formatting mistake (looked like mixture of tabs/spaces getting mixed up). Have switched to nested bullet points and committed.

**Comment by Ryan00793** [comment]
It no longer preserves white space on github but is still readable in raw mode but I would assume that people would like it to be easy to read.

**Comment by gbaman** [comment]
Yeah, that is a feature of Markdown. If you wanted to force spaces, can use `&nbsp;` although that is a bit of a pain.
Simplest Markdown way of doing it is just bold titles (which I have just committed). Or, switching it back to raw text which does look a little ugly :)

The proper way to be doing it really is making Github Issues and assigning them to people etc. Allows comments attached and progress tracking. Takes a little time to set up though.

**Comment by Ryan00793** [comment]
Github couldn't auto merge it so I tried to do it via command line however it wouldn't merge kept saying all files upto date, so i just pushed the changes my self.

**Comment by gbaman** [comment]
Yeah, it would have failed to auto-merge because of https://github.com/Ryan00793/vanillacraft/commit/56ebadf7bcc21f09a0e1ae57b6b99ef49bdc701c as you edited the todo list stuff which I had also edited.
Git is good, but not that good :)

**Pull request closed without merging**
